spring:
  application:
    name: film
  cloud:
    config:
      fail-fast: true
      username: testeando
      password: t3st34nd0
      uri: ${CONFIG_SERVER:http://localhost:8888/}
server:
  port: 8081
eureka:
  instance:
    metadata-map:
      appOwner: Jorge Rodriguez
      description: Tutorial Microservicios
    health-check-url-path: /myHealth
    status-page-url-path: /myInfo
  client:
    healthcheck:
      enabled: true