spring:
  application:
    name: turbine-server
  profiles:
    active: ${ENVIRONMENT:local}
  cloud:
    config:
      fail-fast: true
      username: testeando
      password: t3st34nd0
      uri: ${CONFIG_SERVER:http://localhost:8888/}
server:
  port: 8765