spring:
  application:
    name: eureka-server
  cloud:
    config:
      fail-fast: true
      username: testeando
      password: t3st34nd0
      uri: ${CONFIG_SERVER:http://localhost:8888/}
server:
  port: 8761
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
  server:
    waitTimeInMsWhenSyncEmpty: 0
    enableSelfPreservation: true