server:
  port: 8761
spring:
  application:
    name: eureka-server
  profiles: node1
  cloud:
    config:
      fail-fast: true
      username: testeando
      password: t3st34nd0
      uri: ${CONFIG_SERVER:http://localhost:8888/}
eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
    enableSelfPreservation: true
    
---

server:
  port: 8762
spring:
  application:
    name: eureka-server
  profiles: node2
  cloud:
    config:
      fail-fast: true
      username: testeando
      password: t3st34nd0
      uri: ${CONFIG_SERVER:http://localhost:8888/}
eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
    enableSelfPreservation: true