spring:
  application:
    name: eureka-server
  profiles:
    active: node1, node2
server:
  port: 8761
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
  server:
    waitTimeInMsWhenSyncEmpty: 0
    enableSelfPreservation: true