spring:
  application:
    name: Config Server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jorgerod/microservices.git
          basedir: config-server
server:
  port: 8888
security:
  ignored: /health**,/info**,/metrics**,/trace**
  basic:
    enabled: true
  user:
    name: testeando
    password: t3st34nd0